// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skwjcpvaqknmvsmlzstt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrd2pjcHZhcWtubXZzbWx6c3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTMyNDAsImV4cCI6MjA3MDk2OTI0MH0.ggbTZcMk3JkueZ9Pbr81vGu6_NiiZWI5aZ0UXiSUEHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});